export type ProspectListItem = {
  id: string | number;
  created_at: string | null;
  search_keyword: string | null;
  search_city: string | null;
  search_state: string | null;
  google_place_id: string | null;
  google_maps_url: string | null;
  school_name: string | null;
  website: string | null;
  main_phone: string | null;
  full_address: string | null;
  city: string | null;
  state: string | null;
  school_type: string | null;
  hs_enrollment: number | null;
  clubs_count_estimate: number | null;
  target_persona: string | null;
  contact_name: string | null;
  contact_title: string | null;
  contact_email: string | null;
  fit_score: number | null;
  enrichment_error: string | null;
  email_validation_error: string | null;
  enriched_at: string | null;
  enrichment_status: string | null;
  contact_email_validation_status: string | null;
  email_validation_status: string | null;
  dedupe_key: string | null;
};

export type ProspectInsertRow = {
  search_keyword: string;
  search_city: string;
  search_state: string;
  google_place_id: string | null;
  google_maps_url: string | null;
  school_name: string;
  website: string | null;
  main_phone: string | null;
  full_address: string | null;
  city: string;
  state: string;
  school_type: string | null;
  source_urls: string[];
  enrichment_status: "raw";
  email_validation_status: "not_checked";
  dedupe_key: string;
  raw_google_json: unknown;
};
