export const HUBSPOT_EXPORT_HEADERS = [
  "First Name",
  "Last Name",
  "Email",
  "Phone Number",
  "Job Title",
  "Contact owner",
  "Lead Status",
  "Contact Rank",
  "Sequence Pick",
  "Sequence Name",
  "Best Contact Reason",
  "Email Validation Status",
  "Company Name",
  "Company Domain Name",
  "Company Phone Number",
  "Company owner",
  "Street Address",
  "City",
  "State/Region",
  "State/Region Code",
  "Postal Code",
  "Time Zone",
  "Industry",
  "Type",
  "Record source",
  "School Type",
  "Religion",
  "School Structure",
  "School Structure Boy/Girl",
  "School Structure Day/Boarding",
  "School Divisions",
  "Low Grade",
  "High Grade",
  "# of Students",
  "# of Clubs",
  "List of Clubs",
  "Clubs Letter Grade",
  "% Clubs Get Funding",
  "% Lots of Participation",
  "% Plenty of Clubs",
  "Tuition",
  "Niche Ranking",
  "Number of Employees",
  "Annual Revenue",
  "Subscription Year",
  "Description",
  "LinkedIn Company Page",
  "Reference School",
  "Reference School Reason",
  "AI Fit Reason",
  "Source URL",
  "Data Confidence",
  "Notes",
] as const;

export type HubSpotExportHeader = (typeof HUBSPOT_EXPORT_HEADERS)[number];
